import 'custom_exception.dart';
import 'employee.dart';

main(List<String> arguments) {
int a = 5;
int b = 0;  
Employee employee;

try {
    //throwException();
    int result = a%b;
    assert(employee != null);
  } on CustomException catch(ce,ct){
    print("custom exception is been obtained: $ce");    
    print(ct);
  } on IntegerDivisionByZeroException{    
    print("Divisi칩n entre cero.");
  } catch (e,t) { // e = La Excepci칩n y t = Seguimiento del error
    // Tipo no especificado, manejar치 todo. 
    print('Algo realmente desconocido: $e');
    print(t);
  } finally {
    print("Siempre se ejecutara esta porci칩n de codigo");
  }
}

throwException() {
  throw CustomException('Mi primera excepcion');
}